# .github/workflows/release.yml
name: GoReleaser

on:
  push:
    # 仅当一个新标签被推送到仓库时，才触发此工作流
    tags:
      - 'v*' # 匹配 v1.0.0, v1.2.3 等标签

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 这个设置是必需的，以便 GoReleaser 能获取所有 git 历史来生成更新日志
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5' # 根据你的项目使用的 Go 版本修改

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # 指定运行 GoReleaser 的版本
          version: latest
          # 告诉 GoReleaser 执行 release 命令
          args: release --clean
        env:
          # 这是一个特殊的令牌，GitHub Actions 会自动提供
          # GoReleaser 用它来向你的仓库创建和上传 Release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}